# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - 5

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: DgIsePZMMmrJ1TtTm943TSjnAL205dGOztt1kR1Dj65XjcBGIfbWEXTpNALVliwqTMXHs9EGmz+KRZC5+OGDicjbV7Ykr1B94LLVwOjNW43YN89ok/2Xbk8LXRxtHi6yKxk/LLyHgAw5q8ktqdZ+kdwsli7kqRhdkZOh1j75DXYqj5mFpAXZyDWfWFJNY8Vdnv/Nf9q61pWh/OAnKsC4Dpgtrl2oWs8+kzgZZHhjzecN7TFUfkDA/OWEs+snsvOGts5Kzi3BedsIAp5Sv/aX8gM9iyar4QrO0o6UFICSONzUN/vbi4qiLaCyyPYEMv/c0anGFMcikam/k9DDgqnbXqmo2p8N4nq9zcRz4j9GmI0N6IOH0RRbJHGJNPd0IRJ0Ss1n8uYOj2ApbDi9PspHEmMUbxHEGgm7dF36i8gD/vUwfCiuuqhrkjJmw28ccrf2adBAt1fYrwiPaZKo4LSoAivew5y39rQVyoWwxQGu930dmDxTTQCwzlOVSkq85VVpYNhWBBSWcA4bOF0Ns7lLte1sIvgJAUPHdTCql58He6MrjOzJ1a4DSucvRCa3VdmdDSOmK/WUdxWEAz8WFsY0GB9QaFJD4yhpXmj8PA5Y8SSnBpyVtXUE+Jx/H90lS1tJb8jMCPorVHUDb1HbhSBh22YTjIIhLvkLdmooZcLOJrk=
    # SAUCE_TOKENS
    - secure: ZW8WTdVgeT6XJtfCCoE9q1yiDBwJBbLVauxzxK2qMlxWSwB5KDeMa/nXlsUBprqCE/uYXk28NQW0b6SUF0iFUL6Ig5zQ5s0MOx+wLoUU4VgMMkv1H98Z3XNoM77iDc+ZP3BO/XAU24UtPYwU2NaFjgFPbqnccYxHGPFLNUXTVzqpVE0KuCMRfGQCtwGZt2JKDmSuyZo5FdBztFZfoLOFu0hpW1nUR6dGaTVtGVrwWehuGr6NoNNPs/RbMTzEYqa1xKBMlflQQ0B0peCO5OrWQzzAWIjJIEBwjfCwgayRPWDVoQKwH2WDoTEfe6D/RD2IDcbAgfkd8egQ/VaF28u/FNZicgVnRbU5fnmDIZTqlSc34te9tfsw6F1M+PzMoq0iFeQVfB9TbCTHf8fBEsq9Dk82wzZrlKFVjXwTr598BF8vE3x5et9rYVXZXEge7jvCKfF3q4TKF2/Sa7AyDp3uXJIfM8C9//Rpq5irgGeXDQ+yO5dZhAsa6hHNVisjRVD1K71wRfVElyUKYvU8oYlRd2dripZtgfN55SS0oMvAoT0FbUt6QVL1//Csd0zVjgmopdbLybRPlHU+QlL/BZFbP5cKqwQgoIcMlhzu9+FiVcwu7cKTyqXlB6+/imFXojh6dJOhhDVga4ttrSjwvWI+Z+skss0d1b0oGn2Z0gLdJU4=
    - secure: IQnriUwtzFsL9YVZ7MgOzgktuXBn4OzcdKXrO6qEPh4kNeDKieGOb1D6bQBXb3sl7PA5BaZeyzgDi8cwIL4/E1JzUw6m++L6tYvB0rX0lSx+Jzp0zYs3UfCyb5c/VxOPdyEgNGLOSMJl392soQY5kYmdqPm20pkcSFIZPklG/nvqOPHS77/25k4wLUw6M/pSrm03bral5ndflFvuyCzRHlJYwS7bSH2nmV9040NYa2OnK2sR+XwBKc6n1iQhGrUCKMpDoWOCOnjcyNmCUfmAlnbadjn2K1AN70UbTmuWQ4+EGbxTrMfcwIjx7DzGVJRCo9hsNN226UnKDITYzxZdT//EA2AU/OQ+M/MJztyWk3V68EtDIs+wybBKquTJ1KTavA7oJyfU9UDvkFWYtwJ34PCruOc+dEFt3cIxRKS1uPq8mdioegRGzRD63PgQmR1X8nYxMYvvb1w/tgu0X7NLR1PCLHjHI7s4dd4ug3FfjnqXx14GovTVgTGnKfmtM1bfzWWhGWpqUIcytnU2qThhcB/sjEadGM/EsmhnTqlTTonHQe0f3qwECqcWczlGFPVt0zCOpeamHWfhzvVD0F/NFBRHviKY/LLQn8wUdu1tTv/ovCzqiJvHsVDCStxAdQvuruskrtnuAqQ0OHSA6lX0/mGa3UhlI2umgsf93CS7Trs=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: S4uaWWidiYuhNhld9j+J4ABywPvAW3jswbDgPAUf+Xnk7TAP5S61pIg7pJqONH6vTwQfPrfg8kRMK47WSVxiKoMgzVY71V3DnFGqxMiEYoAhx3uPW9zoEg1+UVrpCrqGg0snj1Q1cUTTYgRXcyba4r4PhY6r7joQSzw1eYSI2VzYUEqFZLeu6X9+nZmHby5/3MuTp1/4iQkip5+XYVFlY2uZkPiDSbgGKYCdV1H6pbPJqF+NeVZwXP72ggwUL+tMkNTolXXLuR1og6+Sre0t9udXVW3re2FEuE4/iIUqMW7PoVTXes/RnTWMpg7wFmqudCSlVqIvuw6Y3BfIUZBtK+t3x97un07/epXvhHC7V7XMAv0JOwSYfWT+9p4nKWI4QQpXNoC236gALKOK23dAh4r4ddIJxBxEiGFp/G0Vzx6/IjmsTy/d+6/9QN05jA8FpNEfB9QRJ1X4zyFj0SZXUTCsw+qVrDs21bBl0gqk36L+OJu1VqtcGuso5HW9rI6tAcYM2uMen6V3PxuQsyvHdmrYqb1LnWVCHYTs32n+wV+IovqqsFADxRlj6qRxdqNUiRq6MjTTuedGupaz/tOkS5rw3WDf/1TN6Vr0Ta9qlmAKE9aB5T5sBhEIESExGvin481MqEaLEFjLKK18jzIH6Ztp+vXmXMrEhYdIbqVVS2k=
  on:
    node: 5

# Cloud testing
after_success:
  - npm install
  - npm install zuul
  - npm run test-cloud
