# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: DgIsePZMMmrJ1TtTm943TSjnAL205dGOztt1kR1Dj65XjcBGIfbWEXTpNALVliwqTMXHs9EGmz+KRZC5+OGDicjbV7Ykr1B94LLVwOjNW43YN89ok/2Xbk8LXRxtHi6yKxk/LLyHgAw5q8ktqdZ+kdwsli7kqRhdkZOh1j75DXYqj5mFpAXZyDWfWFJNY8Vdnv/Nf9q61pWh/OAnKsC4Dpgtrl2oWs8+kzgZZHhjzecN7TFUfkDA/OWEs+snsvOGts5Kzi3BedsIAp5Sv/aX8gM9iyar4QrO0o6UFICSONzUN/vbi4qiLaCyyPYEMv/c0anGFMcikam/k9DDgqnbXqmo2p8N4nq9zcRz4j9GmI0N6IOH0RRbJHGJNPd0IRJ0Ss1n8uYOj2ApbDi9PspHEmMUbxHEGgm7dF36i8gD/vUwfCiuuqhrkjJmw28ccrf2adBAt1fYrwiPaZKo4LSoAivew5y39rQVyoWwxQGu930dmDxTTQCwzlOVSkq85VVpYNhWBBSWcA4bOF0Ns7lLte1sIvgJAUPHdTCql58He6MrjOzJ1a4DSucvRCa3VdmdDSOmK/WUdxWEAz8WFsY0GB9QaFJD4yhpXmj8PA5Y8SSnBpyVtXUE+Jx/H90lS1tJb8jMCPorVHUDb1HbhSBh22YTjIIhLvkLdmooZcLOJrk=
    # SAUCE_TOKENS
    - secure: WzkXy99jTVCzrEYYw8ZvDgcWuyxwKK6Z6OD8BZhx4mb1ou2nbFYH285OPSsyYIjzPM0Zuptw4czwfUGQfoAnfv/3oZ95sBURWyeEm8RBcevplHQ3g2T2pXiEkjjc9ZFglFf9j8MkGgzqi2A/DPQkx1mLmPz2+M1le3PJc8k1XPnHRJbxlSm0NdEsPtXLqZxIgFvAJThlM05/cEayFYCcRXiOC/S99hP/BS1U64cT+GYf2BBKxtqyWPFuaf/qiRCb7TWMKPu5fbzLkDf2H/2/PX7okISSOt6dqzpNdDuL59BdSpCo6R169zWqJetZosr8fGhUBcpe24lCtepsp0V7y/rXanT76ipURcsQAXE4VRzKIDo4KUoYa1gJwdA/XgZxzRvxmijjp6Yd9wDxbUYr5l8D6VivbCmxuJkZL5xJ3yZ36eEj74Y85e6pltl2iHS3FwQflob7rhnLaPwwkmRtyeMAzFcRq/1yPm/iu2xEDvH5Scj/aWDYMrDtY1VqP2mZsPuAgQneSAqA1l/s4GExnNppgB4dLTlJ8EsrH1vN/MoJ4PHHHth/pJSfdb57LJ8Vz/TIwaH5n6+lXNpu7B6CW74D7z4xjABDSuGSUtE59+5K2to0mG8qxxGYCiZVP80WGGE0C7zgbSA1VyN+tzM8L89oIfKC+0qb6lVWWWgW8tg=
    - secure: jsG++N6uJ4DwpQ6CsrJoBjaspGFk9G+2Hf3hYJWDDM2jZ7T/3Ip9jmDX7QTrKQT/m/4xSWYQPhRsCuxpgyhCMe/OKA/gc0xXOSaYUrtUihFVX2OvGBiC4XQLjnkJehOgwFN8CgVQIT69juQcSHUu26oiZKsZ/Jh1zhyYbq5/bWhZ+g9TWr8xHLNGbMRbinKPxLE7vzk87JgIaMTa8oN/l1PpDVZoyjDxsYGZYdohH+7QN4eL9uuUsf7uR+/sHIutSBs5g+BDHpwSyIHYOwloR6nuTOGn4eRFoPqSPdkOgL5iQ/0YPC8aTHVG4q7nTiyYULaJkJv8L5z7kzGqP2H2pXi0B96wr8/ur3i14F7KyiEmtcdBGO8wODVCwXpDCIbU+aAkEjtCKwVpv4BIRYoDqSpxCI84+heXY0VjEpzLZuC4ygbXWLsq2bSeF/7ka2fe4T3VGwcATSgxJDV4f8t6jy56E+gWCMJHlsAgHRd5w/JOQQEuOaRfrd5PCTFTL4Fe04uX4vvwgvvcWLpqWTbGupWsZ2T6NoKbtMEJ7ReVPH9qKiJhjI8mJhu+41ULKlCKF3p9R5imRmIiatC4V/2ac/3qZNVm9/x3DJ7fin0wCvrB7fkNr9npJVsyv72k6qmZH8KuWg5f62b9ahsMgnbfgiQ+acT5vAwj/EB4SVvy3RE=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: MZWBIfCOHXftz8dYmyXOcNW6P/g6GNclw9zisQIM3P9l48r5q6irK3VEGGnEecOlJmFrtw2LItckPpEyJe7KZHo/stZrBPBz4bmS7KdaLCiKkiJvWGCBHQBvE+DOeKVvAY3mLuFJN+Pcs2MIL0DlMC+/m3o7ASRsnEt84vAR9nZDujDKxt3i448CWIu2YR94B9zCYU+8h8ZSiCZ2t5zK7/XySWUAITowxIp9JrA7yXMQST4e/V2e5mHsqrdXxX7fpqEubFpqtgkKaFAbZGKU8FpKBypA4FP5GLxG67NFLiq2AjHp9XaR+vb15e7hthfw9F9IT0nWXJprvNPyA5XNcRqkZXCIZYCG7kkNMvbILKKkmFqmT23wKWXwXh1QLfjlpUgkKsBEMdluWBkQUPHp7S6B2zgqyeW1xdjoUFOfBpkCijWNAK1ulGWdrR1kMlxZjEf3TDtX8tmt9Al/JxVtM129QmiszWSw1+5dWZ9fbW3NJhpSQt81QfS3R1XithfYpamas2xIxmO54rpTiriqemlUnX4eID+AyGLHBog+T7LN1p0nyHIqkd5b/+mKDsjZ9JGO4cB+oQ76buXSrVyi3XW/+gn7D0jYNlflUltFQvFJD/RSW6MSVTFNu8ht+AurINKe5YrPOoIzEarp/4uW+fTOrNyaUxUu3ZsRWVnqgNU=

# Cloud testing
after_deploy:
  - npm install
  - npm install zuul --global
  - npm run test-cloud